name: Sync Common Files
permissions: write-all

on:
  schedule:
    - cron: '0 0 * * *' # Runs nightly
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Common Files
        uses: BetonQuest/CommonProjectFiles@main
        with:
          ignored-files: mvnw,mvnw.cmd,.mvn
